### ISSUE TITLE
Request: change void/background color.

### ISSUE THREAD

**Issue by nobodyinteresting** [lordmir/landstalker_editor#32]
It'd be great if there was a way to change the void color to something other than black for ripping purposes. Currently, even if you export as a PNG, it comes with a solid wall of black behind it (which is a color the game uses a lot, so you can't even just select all black and remove).

Apologies if this is already an option somewhere. Also, phenomenal work - I did not expect to come across a functional Landstalker viewer/editor!

**Comment by lordmir** [comment]
In most of the editing screens, there should be an option to change the appearance of the background and other transparent regions from black to a grey/white checkerboard pattern.
The exported PNG files should have transparency enabled. You may need to use a different image viewer to see true transparency - MS Paint, for example, doesn't fully support displaying PNG transparency.

**Comment by lordmir** [comment]
The toolbar button to use for enabling/disabling transparency looks like the following:
![alpha](https://github.com/lordmir/landstalker_editor/assets/12159525/7cf72e2e-8023-4d23-b0b5-cca519b137ea)
Note that the room maps do not currently support alpha for technical reasons, as the game often uses black sections to hide graphics on lower layers, bot all other game assets do support transparency.

**Comment by nobodyinteresting** [comment]
Yeah unfortunately it was only room maps I was looking at, as I'm currently trying to rip the maps for personal use. Since some emulators allow you to change the background black to magenta, I was hoping there was a way to do that in the room map viewer: [https://files.catbox.moe/05fvq0.PNG](url)

Regardless, thank you very much for all the work on the editor 8)

**Comment by lordmir** [comment]
Hey, just coming back to this request. The latest release (v0.3) of the editor now supports changing the background colour of the room maps to transparent.
