### ISSUE TITLE
What disassembly to use?

### ISSUE THREAD

**Issue by OrangeSkies2** [lordmir/landstalker_editor#33]
Hello, I am working on my Landstalker ROM that I hope to release later this year in your Landstalker Editor program, and was wondering what disassembly I should use? Should I use this one labeled "landstalker_disasm" (https://github.com/lordmir/landstalker_disasm) or this one labeled "landstalker_disasm_working" (https://github.com/lordmir/landstalker_disasm_working)?

If i should be using the one labeled "landstalker_disasm", should I use the "landstalker_us.asm" file or the "landstalker_us_expanded.asm" file? 

I was wondering because whenever I seem to edit too much of the game, go to build the rom, and it says I should use a disassembly file to build the rom and I accept, the ROM always seems to crash in my emulator after doing something simple like starting a new save file or entering the first room.

Also, is it better to edit the game via a .bin or .asm file? What would you reccomend?

Sorry for all of the questions and if this is a dumb question , I am new to the editor.
Thanks !

**Comment by ner00** [comment]
> I am going to try to make a Landstalker romhack that greatly changes the game.

Being a beloved game from my childhood, I can't wait to see what people can do with this toolset.

**Comment by lordmir** [comment]
> Hello, sorry for the late reply! Thank you so much for your reply, I greatly appreciate it! This helps a lot! I am going to try to make a Landstalker romhack that greatly changes the game. Thank you so much for your work on the editor, it is great!!

No problem, I'm currently working on some new features, including full map editing. I'll be really interested to see what you come up with!

**Comment by OrangeSkies2** [comment]
> No problem, I'm currently working on some new features, including full map editing. I'll be really interested to see what you come up with!

Wow, that sounds super amazing!
Thank you so much for your support!
